name: codecov
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get flutter packages
        run: flutter pub get
      - name: Run tests and generate coverage report
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        run: curl -s https://codecov.io/bash
        shell: bash
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage/lcov.info
