name: Dart Code Metrics
on: [pull_request, workflow_dispatch]

jobs:
  dart-code-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Dart Code Metrics
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get
      - uses: CQLabs/setup-dcm@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: dcm analyze --ci-key="${{ secrets.DCM_CI_KEY }}" --email="${{ secrets.DCM_EMAIL }}" lib
